### ISSUE TITLE
Will you provide you opencl cracker one day ?

### ISSUE THREAD

**Issue by bbaranoff** [MidnightBlueLabs/TETRA_crypto#1]
Hello as in object will you provide your opencl cracker ?
![Capture d’écran du 2024-02-23 20-46-42](https://github.com/MidnightBlueLabs/TETRA_crypto/assets/37385191/91ce8449-fa09-4e3d-9644-bdfff2cc621f)

**Comment by romanremus** [comment]
hello bbaranoff, there is a tetra decryption software here with a known key, but I hope that Midnightblue will be patient one day and help us find a key, once the TEA encrypted lot has been found, congratulations to them, what's the point of not he also helps us with finding a key   https://github.com/osmocom/osmo-tetra

**Comment by bbaranoff** [comment]
If I have understood we can find the key by bruteforcing a ciphered burst with ta60 d to match with the non ciphered one or a non ciphered one with ta60 e to match with a ciphered one ? And make bruteforce on GPU with OpenCL ?

**Comment by carlicious** [comment]
Hi there. Thank you for taking interest in our research. As a matter of principle, we don't publish attack code. Instead, I'll point you to some public resources that are, well, public anyway.

Firstly, there's the [reverse-engineered TEA1 cipher](https://github.com/MidnightBlueLabs/TETRA_crypto/blob/main/tea1.c). You can immediately spot the backdoor: `tea1_init_key_register` takes an 80-bit key, and returns a 32-bit integer, which is then used throughout the cipher going forward. Thus, this 32-bit key is all you need to decrypt messages going over the air, regardless of the original 80-bit input that was fed to `tea1_init_key_register`.

Secondly there's the [academic paper](https://cs.ru.nl/~cmeijer/publications/All_cops_are_broadcasting_TETRA_under_scrutiny.pdf), stating the following:
> In order to increase transmission reliability, certain signaling messages are transmitted several times, such as messages related to channel allocation. Analysis of live TETRA traffic shows that such retransmissions are frequent and easily identified by looking for four messages with the same destination, MAC header and length, transmitted at a constant 1-frame interval. Since the repeated messages are sent at different timestamps, their corresponding keystreams are different. However, assuming that the cleartext of these messages are identical, they should yield the same message after decryption. By computing keystreams for all repetitions of the message, we can distinguishing correct from incorrect key guesses by verifying whether the messages are indeed identical after decryption.

In layman's terms: in order to recover the key, one captures traffic from a network with osmocom-tetra, and looks for a pattern of repeated messages (typically 4) with the exact same data found in the MAC header (which is itself not encrypted and contains, among other things, the PDU type, destination SSI, and message length). The assumption is that all 4 messages yield the same contents after decryption. Based on that assumption, one tries to "decrypt" these 4 messages using each of the 2^32 possible keys (a simple for-loop will suffice). The key that yields the same contents for all 4 messages after decryption is the correct key. Osmocom-tetra's decryption is invoked [here](https://github.com/osmocom/osmo-tetra/blob/86796c6c4af263e4831503cbbc4e61c40f0a0ca4/src/tetra_upper_mac.c) on line 194.

Of course it won't be as fast as an optimized OpenCL implementation, but even a very naive implementation should find the key in under 30 minutes on consumer hardware in today's era. In typical circumstances keys rarely change or don't change at all, so optimizing the attack to such an extent is usually not something of much use besides perhaps a fun exercise.

That's all I'm going to share. Best of luck :)

**Comment by bbaranoff** [comment]
Thank you for your time I willtry to understand the best I can when convenient. I should close now

**Comment by romanremus** [comment]
hello carlicious, and thanks for the answer, but what option could we use to find a TEA2 key, which we can later insert into the Osmo-tetra code, and finally enjoy the tetra system, as I am also a radio amateur , once again thank you

**Comment by carlicious** [comment]
> hello carlicious, and thanks for the answer, but what option could we use to find a TEA2 key, which we can later insert into the Osmo-tetra code, and finally enjoy the tetra system, as I am also a radio amateur , once again thank you

The short answer: You can't. The purpose of TEA2 is to prevent exactly this from happening.

The long answer: Since TEA[1,2,3] have been kept secret for all these years, they were never publicly scrutinized, and perhaps their designers have overlooked some issue that allows an attacker to recover a key without having to try all 2^80 candidates. In the coming years, we hope that professional cryptographers will have a look at these algorithms and report their findings. This is why we published these algorithms in the first place: so that hopefully end-users ultimately can become informed about the actual security guarantees that TETRA offers, rather than those advertised.
Personally, I don't expect TEA2 to end up in the realm of being cracked on consumer-grade hardware anytime soon. TEA3, on the other hand, 'feels' weaker. However, that's for someone else with a (much) more serious background in cryptography to put their finger on.
As such, TEA2 is not (obviously) backdoored. As things currently stand, you're not going to get around having to try all 2^80 keys. Even with extreme amounts of computing power, this will take at least dozens of years. Therefore, cracking the key is not a serious avenue for eavesdropping on TEA2-encrypted communications. With the necessity of such vast amounts of computing resources, other avenues become more interesting for an attacker, like the keystream recovery attack ([CVE-2022-24401](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-24401)), wiretapping the communications upstream (the landline is not encrypted), finding and exploiting a vulnerability on an end-user device, an implant or simply bribing someone, just to name a few.

**Comment by romanremus** [comment]
ooooo thank you very much carlicious, at least now I will take my advice from tetra, I tried dozens of times but nothing, but I understand that if we knew an 80-bit key in the tetra software, it could decrypt all the traffic? unfortunately in my country all etra channels are with TEA2, I had high hopes with the osmo-tetra code but I will stop this time, Thank you

**Comment by carlicious** [comment]
> ooooo thank you very much carlicious, at least now I will take my advice from tetra, I tried dozens of times but nothing, but I understand that if we knew an 80-bit key in the tetra software, it could decrypt all the traffic? unfortunately in my country all etra channels are with TEA2, I had high hopes with the osmo-tetra code but I will stop this time, Thank you

Of course, there's not a single 80-bit key that allows you to decrypt all TEA2-encrypted traffic worldwide. Rather, each TETRA network uses its own keys. Furthermore, there's the notion of a so-called _Security Class_:
- in Security Class 1, there's no encryption.
- in Security Class 2, all traffic is encrypted with a single network-wide _Static Ciphering Key (SCK)_.
- in Security Class 3, there's a mandatory authentication step for each client device, yielding a per-client _Dynamic Ciphering Key (DCK)_. Traffic intended for a single client device will be encrypted with this key. However, typically, most traffic is sent to _groups of clients (i.e. talk groups)_, for which a single network-wide _Common Ciphering Key (CCK)_ is used, thus pretty much the exact same thing as the SCK in Class 2. Finally, a group-specific _Group Ciphering Key (GCK)_ can be configured, but if it is not set, the CCK is used instead. As far as I'm aware, the use of GCKs is rare.

Clearly, the networks around you are either Class 2 or 3. The SCK or CCK, depending on the security class of the network, is the closest thing to a key that "could decrypt all the traffic". These keys can have a limited lifespan though (anywhere between a few weeks and forever), as the operator can send over-the-air key updates (encrypted, of course).

Anyway, without any of these keys, osmocom-tetra won't help you decrypt TEA2.

**Comment by romanremus** [comment]
I think you are the only one who can extract keys in TEA2, carlicious, I installed a plugin in sdrsharp called tetra plugin, and security class I have security class 1 support on cell and below security class 3 support on cell, there were long periods in which air interface was 0 and then air interface was 1, I saw in osmo-tetra a keyfille function, there I tried adding some information, namely mnc mcc, but again I was stuck at that key, honestly I thought that if I have some network information with the tetra encryption function, namely ge_ks, I will be able to generate a network key, and yes, you are right, in the network I have SCK

**Comment by hassanTripleA** [comment]
Thank you for posting the issue and thanks for all replying, please how can we capture 4 keystreams? Is osmocom-tetra could make it

**Comment by hassanTripleA** [comment]
How to use the 32 bit eck in osmocom tetra?
